### PR TITLE
Handle terminal close event (FSI)

### PR DESCRIPTION
**Pull request by kirill-gerasimenko**
Hi,

This PR is my attempt to fix the behavior mentioned in https://github.com/ionide/ionide-vscode-fsharp/issues/161#issuecomment-249567249
Briefly - when I close terminal from the toolbar in @code I'm not able to start FSI anymore.
Now with addition of window.onDidCloseTerminal and Terminal.processId it is possible to track this situation. Since Terminal.processId is Promise<int> I had to "promisify" some methods in FSI module. 
The change involves changes in ionide-helpers repository. 

Please let me know what you think on this? If there is something you don't particularly like in the implementation I'm willing to fix that as well.

### CODE REVIEW

**Comment by Krzysztof-Cieslak** [comment]
I think it looks OK. Please PR changes to helpers :)

**Comment by kirill-gerasimenko** [comment]
Will do, thanks!

**Comment by Krzysztof-Cieslak** [comment]
Thanks a lot!

**Comment by kirill-gerasimenko** [comment]
You merged faster than I double-checked, but all works, thanks! :)

**Comment by Krzysztof-Cieslak** [comment]
Released in `2.6.13`

**Pull request merged**
