### PR TITLE
Extract shared line lens and pipeline hint code

### PR DESCRIPTION
**Pull request by faldor20**
### <samp>🤖 Generated by Copilot at eed7bb7</samp>

This pull request refactors the code for the LineLens and PipelineHints features, which show the signatures and types of F# expressions at the end of the lines. The code is moved from a single file `Components/LineLens.fs` to three separate files `Components/LineLens/LineLensShared.fs`, `Components/LineLens/LineLens.fs`, and `Components/LineLens/PipelineHints.fs`, to improve the organization and readability of the code. The code also uses a new `LineLens` type and `Instance` values to expose the features as singletons, and updates the references to the features in other modules and the project file.

### <samp>🤖 Generated by Copilot at eed7bb7</samp>

> _Sing, O Muse, of the skillful refactorer who moved the code_
> _Of LineLens and PipelineHints, the helpful features divine,_
> _To separate files, with shared types and functions, for clarity and ease_
> _And updated the references, the project, and the activation, with care and grace_

📁🔧🚀

### WHY
The line lens and Pipeline hint code has significant duplication. I have attempted to share as much code as possible. This was initially motivated by investigating how difficult it would be to port this feature to the ocaml vscode extension

### <samp>🤖 Generated by Copilot at eed7bb7</samp>

*  Move the code for LineLens and PipelineHints features to separate files and modules for better organization and readability ([link](https://github.com/ionide/ionide-vscode-fsharp/pull/1895/files?diff=unified&w=0#diff-1b61f4c4cffc4a09c37a7f8f70e16971e29dea3c1a8de9a9e8177bc8ffda4e40R1-R151), [link](https://github.com/ionide/ionide-vscode-fsharp/pull/1895/files?diff=unified&w=0#diff-ec3ce02539a0733ff5606b4a6628e9bad7a047496d3cbb33e128b5334b414103R1-R322), [link](https://github.com/ionide/ionide-vscode-fsharp/pull/1895/files?diff=unified&w=0#diff-dbab5b128338ebe31e4a7f519fa49fb3c35e53a8ef76615c0f78afe15ada4da6R1-R81), [link](https://github.com/ionide/ionide-vscode-fsharp/pull/1895/files?diff=unified&w=0#diff-7ce008558fde77b6ae155d9dd49fd4049f622448fc7704e98f8f7bea68977682))
  * Create a new module `LineLensShared.fs` that contains common types and functions for managing the decorations that show the signatures and types at the end of the lines ([link](https://github.com/ionide/ionide-vscode-fsharp/pull/1895/files?diff=unified&w=0#diff-ec3ce02539a0733ff5606b4a6628e9bad7a047496d3cbb33e128b5334b414103R1-R322))
  * Create a new module `LineLens.fs` that contains the code for the LineLens feature, which shows the signature of functions and values at the end of the line, and uses the `LineLensShared.fs` module ([link](https://github.com/ionide/ionide-vscode-fsharp/pull/1895/files?diff=unified&w=0#diff-1b61f4c4cffc4a09c37a7f8f70e16971e29dea3c1a8de9a9e8177bc8ffda4e40R1-R151))
  * Create a new module `PipelineHints.fs` that contains the code for the PipelineHints feature, which shows the type of expressions in pipelines at the end of the line, and uses the `LineLensShared.fs` module ([link](https://github.com/ionide/ionide-vscode-fsharp/pull/1895/files?diff=unified&w=0#diff-dbab5b128338ebe31e4a7f519fa49fb3c35e53a8ef76615c0f78afe15ada4da6R1-R81))
  * Delete the old module `Components/LineLens.fs` that contained the code for both features ([link](https://github.com/ionide/ionide-vscode-fsharp/pull/1895/files?diff=unified&w=0#diff-7ce008558fde77b6ae155d9dd49fd4049f622448fc7704e98f8f7bea68977682))
  * Create `Instance` values that expose the `LineLens` type as a singleton for each feature, and use them to access the features from other modules ([link](https://github.com/ionide/ionide-vscode-fsharp/pull/1895/files?diff=unified&w=0#diff-1b61f4c4cffc4a09c37a7f8f70e16971e29dea3c1a8de9a9e8177bc8ffda4e40R1-R151), [link](https://github.com/ionide/ionide-vscode-fsharp/pull/1895/files?diff=unified&w=0#diff-dbab5b128338ebe31e4a7f519fa49fb3c35e53a8ef76615c0f78afe15ada4da6R1-R81))
* Update the project file to compile the new files and modules and remove the old file ([link](https://github.com/ionide/ionide-vscode-fsharp/pull/1895/files?diff=unified&w=0#diff-9609f7e561702edf7075a23210e8a85dfce7d72c17cd3aa75507dcc1e99cfe07L1-R55))
  * Add the new files `Components/LineLens/LineLensShared.fs`, `Components/LineLens/LineLens.fs`, and `Components/LineLens/PipelineHints.fs` to the list of compiled files ([link](https://github.com/ionide/ionide-vscode-fsharp/pull/1895/files?diff=unified&w=0#diff-9609f7e561702edf7075a23210e8a85dfce7d72c17cd3aa75507dcc1e99cfe07L1-R55))
  * Remove the old file `Components/LineLens.fs` from the list of compiled files ([link](https://github.com/ionide/ionide-vscode-fsharp/pull/1895/files?diff=unified&w=0#diff-9609f7e561702edf7075a23210e8a85dfce7d72c17cd3aa75507dcc1e99cfe07L1-R55))
  * Update the order of the files to respect the dependencies between the modules ([link](https://github.com/ionide/ionide-vscode-fsharp/pull/1895/files?diff=unified&w=0#diff-9609f7e561702edf7075a23210e8a85dfce7d72c17cd3aa75507dcc1e99cfe07L1-R55))
* Update the function `activate` in `src/fsharp.fs` to use the `Instance` values of `LineLens` and `PipelineHints` instead of the old module names ([link](https://github.com/ionide/ionide-vscode-fsharp/pull/1895/files?diff=unified&w=0#diff-93605fe63fbdae821d93b1581e0ba8e17939b52f643f7dfb0871423f6f5fd6b2L75-R75), [link](https://github.com/ionide/ionide-vscode-fsharp/pull/1895/files?diff=unified&w=0#diff-93605fe63fbdae821d93b1581e0ba8e17939b52f643f7dfb0871423f6f5fd6b2L89-R89))
  * Replace the references to `LineLens.activate` and `LineLens.deactivate` with `LineLens.Instance.activate` and `LineLens.Instance.deactivate` ([link](https://github.com/ionide/ionide-vscode-fsharp/pull/1895/files?diff=unified&w=0#diff-93605fe63fbdae821d93b1581e0ba8e17939b52f643f7dfb0871423f6f5fd6b2L75-R75))
  * Replace the references to `PipelineHints.activate` and `PipelineHints.deactivate` with `PipelineHints.Instance.activate` and `PipelineHints.Instance.deactivate` ([link](https://github.com/ionide/ionide-vscode-fsharp/pull/1895/files?diff=unified&w=0#diff-93605fe63fbdae821d93b1581e0ba8e17939b52f643f7dfb0871423f6f5fd6b2L89-R89))
* Update the function `private` in `src/Components/SolutionExplorer.fs` to use the `Instance` values of `LineLens` and `PipelineHints` instead of the old module names ([link](https://github.com/ionide/ionide-vscode-fsharp/pull/1895/files?diff=unified&w=0#diff-13ae03b738fb9bcc3ffeb34994ecc2d80e815e98079c87f8e9c0c42fadd2a9d9L788-R789))
  * Replace the references to `LineLens.removeDecorations` and `PipelineHints.removeDecorations` with `LineLens.Instance.removeDecorations` and `PipelineHints.Instance.removeDecorations` ([link](https://github.com/ionide/ionide-vscode-fsharp/pull/1895/files?diff=unified&w=0#diff-13ae03b738fb9bcc3ffeb34994ecc2d80e815e98079c87f8e9c0c42fadd2a9d9L788-R789))

### CODE REVIEW

**Review by TheAngryByrd — APPROVED** [review]
Thanks! Looks good.  

We have some CI issues we need to get dealt with before we merge.

**Comment by TheAngryByrd** [comment]
I can't get this to build locally:

```
.\src\Components\LineLens\LineLens.fs(145,9): (145,56) error FSHARP: Type mismatch. Expecting a
    'Fable.Import.VSCode.Vscode.TextDocument -> Ionide.VSCode.FSharp.DTO.Result<Ionide.VSCode.FSharp.DTO.Symbols Microsoft.FSharp.Core.array> -> Fable.Import.VSCode.Vscode.Uri -> Fable.Core.JS.Promise<(Fable.Import.VSCode.Vscode.Range * Microsoft.FSharp.Core.string) Microsoft.FSharp.Core.array>'
but given a
    'Fable.Import.VSCode.Vscode.TextDocument -> Ionide.VSCode.FSharp.DTO.Result<Ionide.VSCode.FSharp.DTO.Symbols Microsoft.FSharp.Core.array> -> Fable.Import.VSCode.Vscode.Uri -> Fable.Core.JS.Promise<(Ionide.VSCode.FSharp.DTO.Range * Microsoft.FSharp.Core.string) Microsoft.FSharp.Core.array>'
The type 'Fable.Import.VSCode.Vscode.Range' does not match the type 'Ionide.VSCode.FSharp.DTO.Range' (code 1)
Compilation failed
```

**Review by TheAngryByrd — CHANGES_REQUESTED** [review]
I can't get this to build locally

```
.\src\Components\LineLens\LineLens.fs(145,9): (145,56) error FSHARP: Type mismatch. Expecting a
    'Fable.Import.VSCode.Vscode.TextDocument -> Ionide.VSCode.FSharp.DTO.Result<Ionide.VSCode.FSharp.DTO.Symbols Microsoft.FSharp.Core.array> -> Fable.Import.VSCode.Vscode.Uri -> Fable.Core.JS.Promise<(Fable.Import.VSCode.Vscode.Range * Microsoft.FSharp.Core.string) Microsoft.FSharp.Core.array>'
but given a
    'Fable.Import.VSCode.Vscode.TextDocument -> Ionide.VSCode.FSharp.DTO.Result<Ionide.VSCode.FSharp.DTO.Symbols Microsoft.FSharp.Core.array> -> Fable.Import.VSCode.Vscode.Uri -> Fable.Core.JS.Promise<(Ionide.VSCode.FSharp.DTO.Range * Microsoft.FSharp.Core.string) Microsoft.FSharp.Core.array>'
The type 'Fable.Import.VSCode.Vscode.Range' does not match the type 'Ionide.VSCode.FSharp.DTO.Range' (code 1)
Compilation failed
```

**Comment by faldor20** [comment]
@TheAngryByrd This should be fixed now, not sure what happened there, I must have not pushed something 🤦‍♂️

**Review by baronfel — APPROVED** [review]
Nice - this really illustrates the shared workflow between the features. It'll also make it easier to add new kinds of lenses!

**Comment by baronfel** [comment]
Thank you for this!

**Pull request merged**
