### PR TITLE
[WIP] Add Windows Debugger support

### PR DESCRIPTION
**Pull request by Krzysztof-Cieslak**

### CODE REVIEW

**Comment by daviwil** [comment]
Any chance of getting process attach to work too?  It'd be super helpful for debugging the PowerShell language server.  Looks like mdbg provides an attach command so it seems possible.

**Comment by Krzysztof-Cieslak** [comment]
Yes, I'll add it.

**Comment by daviwil** [comment]
You're my hero!  Switching over to VS 2017 just to debug C# code is giving me a rash.

**Comment by Krzysztof-Cieslak** [comment]
Apparently MSFT can do stuff better on their own.

**Comment by Lavinski** [comment]
What's the status on this item?

**Pull request closed without merging**
