### PR TITLE
Update to use FsiAnyCpu.exe by default

### PR DESCRIPTION
**Pull request by denskh**
Update to use FsiAnyCpu.exe on Windows platform to provide better support of 64 bit OS. FSharp.fsiFileName configuration parameter let user specify any other name, ex: fsi.exe.

### CODE REVIEW

**Comment by cloudRoutine** [comment]
rename `FSharp.fsiFileName` to `"FSharp.fsiFilePath" 
change `description` to  `The path to the F# Interactive tool used by Ionide-FSharp"

**Comment by cloudRoutine** [comment]
@denskh  based on input from @Krzysztof-Cieslak I changed my comment ;)

**Comment by cloudRoutine** [comment]
good work on this :+1:

**Comment by denskh** [comment]
Does it look good or do you need anything else done here?

**Comment by cloudRoutine** [comment]
let me checkout these merge conflicts

**Pull request merged**
