### PR TITLE
Fable 1.2

### PR DESCRIPTION
**Pull request by vbfox**
Building works by hand (`dotnet fable yarn-build` in src) & the plugin run with some manual copy-pasting (of project.json) but I still didn't do any work to make either the build script or build from vscode works.

Depends on https://github.com/ionide/ionide-vscode-helpers/pull/13

### CODE REVIEW

**Comment by enricosada** [comment]
LOVE IT!

**Comment by vbfox** [comment]
The build and code seem ok now, it build on appveyor ( https://ci.appveyor.com/project/vbfox/ionide-vscode-fsharp ) and the few things I tested work.

I need to test it more deeply, also I need to build it at on mac & linux once to see that I didn't break the build. But I don't expect the code to evolve much.

**Comment by vbfox** [comment]
Found a few bugs, fixed them I'm pretty happy with the state (Also moved to fable 1.2 stable) but wasn't able to test on mac (mono version broken maybe ?

It can't build FsAutoComplete) and while I tested more features I don't think I have the setup to test everything.

So would need test by someone other than me to check that it didn't break everything :)

**Comment by Krzysztof-Cieslak** [comment]
@vbfox: Needs rebase.

**Comment by vbfox** [comment]
Rebased (after fighting with https://github.com/fsprojects/Paket/issues/2751 )

**Comment by Krzysztof-Cieslak** [comment]
💟

**Comment by vbfox** [comment]
@Krzysztof-Cieslak  cool, i'll do another PR to change paket.dependencies when https://github.com/ionide/ionide-vscode-helpers/pull/13 is merged :)

**Comment by Krzysztof-Cieslak** [comment]
Fuck, forgot about helpers... ionide/ionide-vscode-helpers#13  merged.

**Pull request merged**
