### PR TITLE
FSharpLint integration improvements

### PR DESCRIPTION
**Pull request by duckmatt**
* Prefixes warnings from FSharpLint with "Lint: " - partly addresses one problem mentioned in #148
* No longer run FSharpLint when it's disabled via the configuration - addresses #150

### CODE REVIEW

**Comment by Krzysztof-Cieslak** [comment]
Thanks for handling this.

It looks good for me, what are further plans?

**Comment by duckmatt** [comment]
I haven't yet managed to test this PR, so will give it a few runs on a few projects to make sure it's not introducing any bugs. I have plans to improve the config API in FSharpLint with the end goal of being able to toggle rules off via the intellisense bubble (or right click context menu), but I think that'll be another PR in the future until the work on the FSharpLint side is done

**Comment by duckmatt** [comment]
Given it a run and it seems to be functioning as expected :)

**Comment by Krzysztof-Cieslak** [comment]
Great, thanks

**Comment by Krzysztof-Cieslak** [comment]
Released in `2.5.3`

**Pull request merged**
