### PR TITLE
Better tooltips

### PR DESCRIPTION
**Pull request by vasily-kirichenko**
image

### CODE REVIEW

**Comment by vasily-kirichenko** [comment]
I also added replacement `<c>xxx</c>` in autocomplete. It does not support Markdown, but backticking is better then xml tags I think.

image

**Comment by cloudRoutine** [comment]
iirc the text content of the autocomplete panes can also be styled via markdown

**Comment by cloudRoutine** [comment]
nope i was wrong markedstrings are only for hovers and decorations

**Comment by Krzysztof-Cieslak** [comment]
That sounds like something what should be fixed in Code.

**Comment by Krzysztof-Cieslak** [comment]
@cloudRoutine will you create issue on their repo?

**Comment by cloudRoutine** [comment]
someone beat us to it https://github.com/Microsoft/vscode/issues/11877

**Comment by EmmanuelOga** [comment]
@vasily-kirichenko: Tangential question, any idea what it would take to provide better tooltips like this on Visual Studio?

Txs!

**Comment by vasily-kirichenko** [comment]
@EmmanuelOga it's possible. I think MS team is working on it right now (Roslyn-style/based tooltips in VS 2017).

**Pull request merged**
