### PR TITLE
use Fake4

### PR DESCRIPTION
**Pull request by enricosada**
- no deprecation warnings
- target net, less dependencies needed

require rebase after #1050 is merged (ci green https://dev.azure.com/enricosada/ionide-vscode-fsharp/_build/results?buildId=65)

### CODE REVIEW

**Comment by MangelMaxime** [comment]
Why not upgrade to FAKE 5 API?

Except for the "less dependencies needed" part which of course would be the same as now. By upgrading, to FAKE5 we would use the stable and maintained version of FAKE. I don't know if FAKE4 is still getting support.

**Comment by enricosada** [comment]
Because is easier to do atm, i just want to avoid the deprecation warnings.

Do do that i just need to restrict the FAKE package version. atm works, i want to push others changes, no time to upgrade

**Comment by Krzysztof-Cieslak** [comment]
TBF, I don't like this - the only advantage is removing of warnings... which doesn't sound as good justification for the change.

**Comment by enricosada** [comment]
Removing lots of warning is the reason. Is a wall of text in the build output. 

I’ll close so, no personal plan to upgrade, no time for that

**Pull request closed without merging**
