### PR TITLE
WIP: netcore MSBuild commands

### PR DESCRIPTION
**Pull request by baronfel**
got bored, this is most of the core logic for #423.  Can't build/test from my laptop due to mono issue that I'm investigating.

### CODE REVIEW

**Comment by baronfel** [comment]
FAKE update fixed it. Having problems with FsAutoComplete 'project' command working when I run the Suave endpoint standalone and send files to it, but not when run from the instance of FsAutoComplete that's started by ionide.

In addition, this PR doesn't successfully build projects that use the new fsproj but target the full-framework, because of the need to specify the FrameworkIdentifier that @enricosada noted in the wiki: https://github.com/dotnet/netcorecli-fsc/wiki/.NET-Core-SDK-rc4#using-net-framework-as-targets-framework-the-osxunix-build-fails

We should possibly extend FSAC to specify the runtime/TFS to build a project for as part of the project request?

**Comment by enricosada** [comment]
@baronfel yes, that's the only way.

I'll workaround in FSAC with https://github.com/fsharp/FsAutoComplete/issues/162 to at least build the **first** target framework specific in `TargetFrameworks`.

but is just a workaround. ionide need to pass a choose a target frameowkr., It's also really really a good idea to add a way to choose the first project or the sln, because otherwise is random (based on first file open, but with old and new in parallel doesnt work)

**Comment by enricosada** [comment]
@baronfel but why add msbuild commands? 

vscode build (CTRL-SHIFT-B) works afaik, just choose .NET Core or msbuild. you can add more targets there 
 ( @Krzysztof-Cieslak that's how vscode works right? launch and build.json)
Shouldnt we add more build target there?

Also msbuild command can be run from terminal afaik.

Also a note. new fsproj DOESNT require .net code sdk (the `dotnet` command). doesnt need to run `dotnet build` or `dotnet msbuild`.
will work normally from msbuild.exe or mono msbuild (mono 5.0).

**Comment by baronfel** [comment]
The commands here are meant to be super simple happy path helpers to quickly compile a single project, not necessarily run your whole solution build. We can definitely use the normal task infrastructure bit that would require more fiddling to detect and build a particular project I think.

**Comment by enricosada** [comment]
Just set the directory or fsproj in the "args" of the "build" command. 
Afaik helper should set that

**Comment by Krzysztof-Cieslak** [comment]
This will be handled bit differently with #460

**Pull request closed without merging**
