### PR TITLE
check all FSI assemblies

### PR DESCRIPTION
**Pull request by jcmrva**
For #1711 

This isn't doing everything I intended, most notably handling the shadowed declarations, but I thought I should get a PR up.

I did manage to maintain compatibility with the single assembly.

### CODE REVIEW

**Comment by jcmrva** [comment]
Maybe I'm losing it. When `folder` in `allVars` is run independently, it gives the expected results. When given to List.fold, the set is updated but the list remains empty. Do I need a different approach here?

**Comment by jcmrva** [comment]
This might be ready to go, aside from the copypasta in the "arrange" functions, which I will clean up at some point.

I noticed `fsi.AddPrinter` is invoked for *each value printed in the REPL*, so...
1. there probably isn't much optimization we can do within it.
2. performance doesn't seem to suffer horribly in spite of that, although I haven't tested huge sets of data.
3. docs should probably come with a warning.

In general, I think we can make it work better by moving some of the code into a better place (FSAC?)

**Comment by baronfel** [comment]
Thank you for your work here! I'll take it for a test drive and roll it into a release in the next day or so.

**Comment by jcmrva** [comment]
I thought it might be a good idea to document my workflow for the change because it's a little unusual vs standard compile-and-run projects.

Background: at a high level, the watcher panel gets values via this process:
1. the `watcher.fsx` file in the Ionide install is loaded into FSI on startup.
2. the watcher function is invoked whenever FSI prints values to the console & saves whatever it extracts from the assembly in `vars.txt`, `funcs.txt` & `types.txt` in the same subdirectory as watcher.fsx.
3. the watcher panel in Ionide refreshes itself from those files, often with a short delay.

The pleasant side-effect of this design is that I could work on the installed watcher.fsx (rather than the Ionide source) and rapidly test changes by only relaunching FSI. No need to retype example code or rebuild Ionide.

I broke the file content formatting early in the refactor, so being able to view the files directly made the feedback cycle even faster.

image

Extending this method to other areas for quick updates & user customization might be worthwhile.

**Comment by baronfel** [comment]
@Krzysztof-Cieslak and I have chatted sometimes about moving from the 'just send/receive from a `dotnet fsi` process model' that we currently use, to having FSAC manage the persistent FsiEvaluationSessions the same way that VS and Rider do to power their 'interactive windows'. That would give us much nicer programmatic access to the bound values and open the door to doing more structured things. So if that's something you're interested in longer term we'd love to have your input.

regarding this PR though, let's ship it!

**Comment by jcmrva** [comment]
Ah, the same method described [here](https://fsharp.github.io/fsharp-compiler-docs/fcs/interactive.html)?

**Comment by baronfel** [comment]
yep, exactly. there would be some book-keeping around identifying _which_ evaluation session a particular interaction command would be associated with, so we'd want to spec out a small set of custom LSP endpoints specifically for dealing with this, but it would be possible to do something like:

* User sends line/selection/file to FSI session via custom LSP endpoint
* FSAC identifies the session by some kind of ID and performs the evaluation of the provided line/selection/file
* FSAC sends any output of the evaluation to VSCode for display
* FSAC extracts the session state after the evaluation using the `session.GetBoundValues()` API and returns that data to VSCode for display in a watcher (if open)

**Pull request merged**
