### PR TITLE
More consistent InfoPanel typography (#1393)

### LINKED ISSUE #1393: Info Panel's formatting doesn't use VS Code's style (font, colors...)
Hey, I'd be happy to help if it's easy to do. I just need a few pointers (how to write the correct CSS so that it picks up the values/colors configured in the VS Code tooling).

**Is your feature request related to a problem? Please describe.**
See title: the formatting is inconsistent with the rest of VS Code (while Quick Info is fine).

image

**Describe the solution you'd like**
Just use the user's UI parameters in the generated CSS/HTML.

**Describe alternatives you've considered**
Don't do anything.

**Additional context**
N/A.

### PR DESCRIPTION
**Pull request by OkayX6**
Fixes #1393 

Very simple theming, makes it less alien. Works in light/dark modes.

infopanel-light
infopanel-dark

### CODE REVIEW

**Comment by OkayX6** [comment]
Interesting, hard to see what was wrong from the logs?

**Comment by OkayX6** [comment]
There we go thanks to #1400

**Comment by baronfel** [comment]
Glad to help :)

Could you please add a 'before' comparison to this issue? I'm having a hard time seeing the comparison without it.

**Comment by OkayX6** [comment]
Sure, here's before the patch:

image

**Comment by baronfel** [comment]
Ah, I see. It makes syntax/links a heavier weight overall, in line with what you see in the editor pane.

**Comment by OkayX6** [comment]
Yeah it mostly use the same font as the one you configure in the text editor, just like the **QuickInfo** tooltip :).

image

Having the same coloring would be a much larger piece of work though.

**Comment by baronfel** [comment]
This LTGM, @Krzysztof-Cieslak do you have any questions?

**Comment by Krzysztof-Cieslak** [comment]
Looks good to me, thanks a lot! 💖

**Pull request merged**
