### PR TITLE
handle filePath with spaces in url

### PR DESCRIPTION
**Pull request by falfaddaghi**
I was not able to build/run the fake file due to a git issue on my pc, but I am fairly sure this will fix the issue. if it does not i will keep trying to fix the git issue.

### CODE REVIEW

**Comment by Krzysztof-Cieslak** [comment]
Git issue is probably SSH key issue, following https://help.github.com/articles/generating-an-ssh-key/ should be enough to get it working

**Comment by rojepp** [comment]
I was going to ask about that. Why not use https for the git deps? It's what I did locally to make it build. Would probably make it easier for would-be contributors.

**Comment by Krzysztof-Cieslak** [comment]
That's reasonable suggestion. I'll change that in some free time... or we accept PRs ;)

**Comment by falfaddaghi** [comment]
I changed paket to use https and how I get this error. Pretty Ironic.
I will move the code to a different workspace and push the pr if it works.

> Message: Could not run "git clone file:///C:\Users\FAISAL ALFADDAGHI\.paket\git\db\FSharpFormatting.CLI".
Error: 
Cloning into 'ALFADDAGHI\.paket\git\db\FSharpFormatting.CLI'...
fatal: 'C:/Users/FAISAL' does not appear to be a git repository

**Comment by falfaddaghi** [comment]
got the project building and my fix is away off i will keep trying .
I am going to close this pr

**Pull request closed without merging**
