### PR TITLE
[WIP] handle known errors of FSAC during project parsing

### PR DESCRIPTION
**Pull request by enricosada**
now fsac return a specific result for known errors

TODO:

- [x] button to `Restore current project`
  - [x] add a `dotnetcli.restore` command
    - [x] call `dotnet restore /path/to/the.fsproj` (path is returned by FSAC).
- [x] after doing `restore` manually works
  - [x] ~need to invalidate current files error and reask FSAC (otherwise squigges remains until you reopen the file). how?~ wait until project parsing is completed after restore
- [x] button to `Restore ...` asking for what proj/sln use. picker? => done, reused all `MSBuild:` commands
- [ ] autorestore setting (false by default) that will restore without asking user
- [ ] remove progress bar, already exists

### CODE REVIEW

**Comment by enricosada** [comment]
first draft => error message
restorerequired



todo:

- [x] button to `Restore current project`
  - [ ] add a `dotnetcli.restore` command
    - [ ] call `dotnet restore /path/to/the.fsproj` (path is returned by FSAC).
- [ ] after doing `restore` manually works, but need to invalidate current files error and reask FSAC (otherwise squigges remains until you reopen the file). how?

ideas:
- button to `Restore ...` asking for what proj/sln use. picker?

**Comment by Krzysztof-Cieslak** [comment]
You can display additional buttons in error popup. For example: https://github.com/ionide/ionide-vscode-paket/blob/b9f00d3dbb812df5c5a2838468976dadc4269c50/src/paket.fs#L71-L73

**Comment by enricosada** [comment]
ok @Krzysztof-Cieslak  found my workflow.

restorerequired2

need some changes (make msbuild command aware of dotnet cli), i'll send a separate PR, otherwise this is too big. This had the notion of msbuild host (`.NET` = msbuild.exe, or `.NET Core` = dotnet cli)
The advantage is normal commands `MSBuild: Build project` will work with dotnet cli too.
Added also a picker to choose and a fast switch commad (msbuild <-> cli) `MSBuild: swtich msbuild host`

Anyway flow is (for not restored):

1. vscode ask `project` to fsac
2. FSAC reply with `projectNotRestored` error
3. vscode run msbuild `Restore` target
    1. user choose msbuild host, if has not already (otherwise current setting)
    2. run with correct msbuild host the `Restore` target
    3. if ok -> retry, otherwise fail

**Comment by enricosada** [comment]
Status, wait on:

- extracted msbuild code ( https://github.com/ionide/ionide-vscode-fsharp/pull/460 )
- FSAC new detailed error ( https://github.com/ionide/ionide-vscode-fsharp/pull/455 )

**Comment by enricosada** [comment]
as a note, latest code doesnt ask for msbuild host to use, and infer is `dotnet`.
Plus progress bar about initialize project and restore

restorerequired4

**Comment by Krzysztof-Cieslak** [comment]
I don't think it's necessary to use progress bar here - we have more general progress bar for plugin initialization (in fsharp.fs) that is enough. 

Also I think we may add autorestore setting (false by default) that will restore without asking user

**Comment by enricosada** [comment]
> I don't think it's necessary to use progress bar here - we have more general progress bar for plugin initialization (in fsharp.fs) that is enough.

restore take time, and also initialization. i'll check if i can directly reuse "loading current project" progressbar

> add autorestore setting (false by default) that will restore without asking user

agree, added to TODO. `FSharp.autoRestore` ?

**Comment by Krzysztof-Cieslak** [comment]
> restore take time, and also initialization. i'll check if i can directly reuse "loading current project" progressbar

Yeah sure, but the progress bar will be visible whole time - just in the state "Loading current project" (or "Loading all projects" if it's restore for other than first projects). Just don't think there is any need for another messages (especially "Project initialization" - this has same meaning as existing messages; I can see the value in having "Restoring" state)

> FSharp.autoRestore

👍

**Comment by enricosada** [comment]
splitted some parts in https://github.com/ionide/ionide-vscode-fsharp/pull/467 too

**Comment by forki** [comment]
What's the status here?
see also https://github.com/fsprojects/Paket/issues/2540

**Comment by enricosada** [comment]
@forki i splitted a bit, because i needed more info from FSAC, and preferred to add small incremental changes to ionide.

Last info i need are in https://github.com/fsharp/FsAutoComplete/pull/187 who add the sdk type to FSAC `project` response (the parsed project info). so i can default to `.net core` commands.

But i'll rebase this, for now i can assume if error is `Restore missing` to use .net core.

**Comment by enricosada** [comment]
i need to rebase another time, probably end of this week

**Comment by enricosada** [comment]
Closing, sending another PR

**Pull request closed without merging**
