### PR TITLE
Language service is returning error

### PR DESCRIPTION
**Pull request by forki**
related #1380 

This won't solve #1380 but it properly propagates the error from fsauto into ionide

### CODE REVIEW

**Comment by forki** [comment]
image

**Comment by forki** [comment]
as you can see the status changed. it's no longer "not restored", but now it's "load failed".

But fsauto returns: Code:102 Message: this project was not loaded due to some internal error.
 whatever that means!?

**Comment by forki** [comment]
@Krzysztof-Cieslak is that build error related? doesn't seem so

**Comment by forki** [comment]
ok one level down the rabbit hole. Maybe this ionide change is just not the right place. I found: 

image

is this correct? Or should this be some kind of error!?

**Comment by forki** [comment]
next step. I followed the trail of that error. I think it's raised inside of 

image

so that means FCS!? Fuck me

**Comment by baronfel** [comment]
That GetProjectOptions is in Dotnet-Proj-Info, so you're safe for a bit :)

**Comment by forki** [comment]
oh I don't mind working in FCS. I meant: that rabbit hole is fucking deep

**Comment by Krzysztof-Cieslak** [comment]
Maybe we could try generating binlog and checking what it says - `FSharp.generateBinlog` setting

**Comment by Krzysztof-Cieslak** [comment]
I'll merge this at it fixes error propagation bug - loading problem needs to be fixed in FSAC/dotnet-proj-info so it's not on Ionide side anyway.

**Comment by forki** [comment]
I wonder if we run in some caching issue here. If I run dotnet proj fsc-args on my repo folder then dotnet-proj-info correctly restores and the prints the fsx params. But what if something between all of this is caching the unloaded state!?

**Comment by isaacabraham** [comment]
This issue hasn't always been around though (in my experience) - I only observed it in the past month or so, maybe less.

**Comment by isaacabraham** [comment]
On a new Farmer project (using Farmer.Template), I can repro this as well. Might not be helpful, dunno, but in the status bar I see: "Not in a F# project (Still loading)". When I mouse over, I get: "Program.fs is not in any project known to Ionide". Meanwhile next to it it shows "Project loading..." for the fsproj and never returns.

**Pull request merged**
