### PR TITLE
Switch out webpack

### PR DESCRIPTION
**Pull request by AngelMunoz**
@baronfel following from https://github.com/ionide/ionide-vscode-fsharp/pull/1721#issuecomment-1153272324
This is a more serious attempt at #1672 this PR takes out webpack stuff and uses rollup, the main reason why we one used webpack + babel (assuming things here correct me if I'm wrong) was mainly to be able to use modern syntax in unsupported browsers (or in this case electron) thankfully everything that Fable emits today is well supported so we just need the bundler and some tree shaking for production builds

I gave it a spin locally and all seems to work just fine but let me know if something is fishy

### CODE REVIEW

**Comment by nojaf** [comment]
> This is a more serious attempt at https://github.com/ionide/ionide-vscode-fsharp/issues/1672

Ouch, that is quite painful to read, to be honest. There was never anything unserious about my PR.
Please review https://github.com/ionide/ionide-vscode-fsharp/blob/main/CODE_OF_CONDUCT.md#our-standards going forward.

**Comment by AngelMunoz** [comment]
I'm sorry @nojaf when I say serious I meant vs my previous attempt which was a mere comment on the original issue, and a deleted branch on my deleted fork, I re-tried to tackle this issue again but in a more positive tone vs my own previous attempts, I didn't mean to cause any harm to you or anyone, I tagged you on your other PR just for us to be in sync. I never meant any harm I'm sorry I didn't phrase that correctly 😔

**Comment by nojaf** [comment]
Apology accepted @AngelMunoz.

**Comment by AngelMunoz** [comment]
closing out in favor of #1684 unless someone else has any other inputs

**Pull request closed without merging**
