### PR TITLE
Mono path setting, promises refactor

### PR DESCRIPTION
**Pull request by kirill-gerasimenko**
Hi,

I've added FSharp.monoPath setting usage to the LanguageService.start. 
During the testing I had some issues with error propagation using current promises implementation so it lead to this [PR-Fix promises #4](https://github.com/ionide/ionide-vscode-helpers/pull/4) in ionide-vscode-helpers project. If it is accepted - than this PR will fix ionide Promises usage accroding to the changes in Promises API. 

Most noticeable change is in LanguageService.start - I've removed usage of continuation lambda passed in start() method in favor of using Promise.create, which has `resolve` and `reject` methods, allowing to shift promise to needed state. Now the promise is resolved when stdout of FsAutoComplete notifies it is started, and rejected, when any error occurs in the started process, even if user specifies wrong mono path in settings and child_process.spawn throws ENOENT error. 

Please let me know what you think on this. 

PS: the automatic build should be failing now, since it depends on Helpers.fs from helpers project, and only will work if [PR-Fix promises #4](https://github.com/ionide/ionide-vscode-helpers/pull/4) is accepted. 

Thanks.

### CODE REVIEW

**Comment by adamchester** [comment]
👍 I had similar plans [here](https://github.com/ionide/ionide-vscode-fsharp/compare/master...adamchester:promisify-langsvc-start)

**Comment by kirill-gerasimenko** [comment]
@adamchester yours looks prettier :) I'll fix Promises.create as you suggested and use Process.onOutput etc. methods as in your branch.

**Comment by cloudRoutine** [comment]
@kirill-gerasimenko now that https://github.com/ionide/ionide-vscode-helpers/pull/4 has been merged run `paket update` to pull those changes into this PR

**Comment by kirill-gerasimenko** [comment]
@cloudRoutine sure, I'll do that and update PR's branch!

**Comment by cloudRoutine** [comment]
LGTM, good job on these PRs

**Comment by kirill-gerasimenko** [comment]
Thanks!

**Pull request merged**
